//! All default settings for neo
use toml::Value;

pub enum Def {
    Bool(bool),
    Int(i64),
    Float(f64),
    Str(&'static str),
}

impl Def {
    pub fn to_value(&self) -> Value {
        match self {
            Def::Bool(v) => Value::Boolean(*v),
            Def::Int(v) => Value::Integer(*v),
            Def::Float(v) => Value::Float(*v),
            Def::Str(v) => Value::String((*v).to_string()),
        }
    }
}

/// (category, key, default)
pub const DEFAULTS: &[(&str, &str, Def)] = &[
    // [gameplay]
    ("gameplay", "boarding", Def::Str("auto")),
    ("gameplay", "pax_prefer_seats", Def::Bool(false)),
    ("gameplay", "pax_rear_entry", Def::Bool(true)),
    ("gameplay", "exact_fare", Def::Bool(true)),
    ("gameplay", "driver", Def::Bool(true)),
    ("gameplay", "maintenance", Def::Int(0)),
    ("gameplay", "collision_vehicles", Def::Bool(true)),
    ("gameplay", "collision_objects", Def::Bool(true)),
    ("gameplay", "collision_pedestrians", Def::Bool(true)),
    ("gameplay", "hands_in_cab", Def::Bool(false)),
    ("gameplay", "time_speed", Def::Float(1.0)),
    ("gameplay", "time_sync", Def::Bool(false)),
    ("gameplay", "metar_sync", Def::Bool(false)),
    ("gameplay", "metar_station", Def::Str("")),
    ("gameplay", "auto_clutch", Def::Bool(true)),
    ("gameplay", "momentary_gears", Def::Bool(false)),
    ("gameplay", "auto_ibis", Def::Bool(false)),
    ("gameplay", "auto_shift", Def::Bool(false)),
    // [controls]
    ("controls", "steering_linear", Def::Bool(false)),
    ("controls", "old_steering", Def::Bool(false)),
    ("controls", "red_steer_spd", Def::Bool(false)),
    ("controls", "mouse_sens", Def::Float(1.0)),
    ("controls", "stick_sens", Def::Float(1.0)),
    ("controls", "stick_sens_v2", Def::Bool(true)),
    ("controls", "steer_center", Def::Bool(true)),
    ("controls", "brake_hold", Def::Bool(true)),
    ("controls", "mouse_steering", Def::Bool(false)),
    ("controls", "mouse_right_off", Def::Bool(false)),
    ("controls", "blinker_cancel", Def::Bool(true)),
    ("controls", "wheel_range", Def::Float(900.0)),
    ("controls", "wheel_lock", Def::Float(0.0)),
    ("controls", "pedal_throttle", Def::Float(1.0)),
    ("controls", "pedal_brake", Def::Float(1.0)),
    // [ai]
    ("ai", "unsched_factor", Def::Float(1.0)),
    ("ai", "max_scheduled", Def::Int(0)),
    ("ai", "max_parked", Def::Int(0)),
    // [ui]
    ("ui", "navigator", Def::Bool(true)),
    ("ui", "opacity", Def::Float(0.85)),
    ("ui", "navigator_corner", Def::Str("bottom-left")),
    ("ui", "scale", Def::Float(1.0)),
    ("ui", "scale_window", Def::Bool(true)),
    ("ui", "notes", Def::Bool(true)),
    ("ui", "show_fps", Def::Bool(false)),
    ("ui", "chat", Def::Bool(true)),
    ("ui", "tooltips", Def::Bool(true)),
    ("ui", "name_tags", Def::Bool(true)),
    ("ui", "language", Def::Str("ENG")),
    ("ui", "units", Def::Str("metric")),
    // [navigator]
    ("navigator", "arrows", Def::Bool(false)),
    ("navigator", "ai", Def::Bool(true)),
    ("navigator", "topbar", Def::Bool(true)),
    ("navigator", "turn", Def::Bool(true)),
    ("navigator", "stoplist", Def::Bool(true)),
    ("navigator", "stops_ext", Def::Bool(false)),
    // [passengers]
    ("passengers", "voices", Def::Str("all")),
    ("passengers", "models", Def::Str("omsi")),
    ("passengers", "motion", Def::Str("natural")),
    ("passengers", "ik", Def::Bool(true)),
    ("passengers", "density", Def::Float(1.0)),
    // [discord]
    ("discord", "status", Def::Bool(true)),
    ("discord", "app_id", Def::Str("")),
    // [graphics]
    ("graphics", "graphics", Def::Str("vanilla_plus")),
    ("graphics", "graphics_api", Def::Str("auto")),
    ("graphics", "window_mode", Def::Str("windowed")),
    ("graphics", "vsync", Def::Bool(true)),
    ("graphics", "max_fps", Def::Int(0)),
    ("graphics", "msaa", Def::Int(4)),
    ("graphics", "anisotropy", Def::Int(8)),
    ("graphics", "post_aa", Def::Str("fxaa")),
    ("graphics", "render_scale", Def::Float(0.0)),
    ("graphics", "ssao", Def::Bool(true)),
    ("graphics", "shadows", Def::Bool(true)),
    ("graphics", "shadow_size", Def::Int(2048)),
    ("graphics", "shadow_blobs", Def::Bool(true)),
    ("graphics", "shadow_casters", Def::Str("all")),
    ("graphics", "detail_textures", Def::Bool(true)),
    ("graphics", "reflections", Def::Bool(true)),
    ("graphics", "clouds", Def::Bool(true)),
    ("graphics", "texture_compression", Def::Bool(true)),
    ("graphics", "texture_memory", Def::Int(0)),
    ("graphics", "min_obj_size", Def::Float(0.013)),
    ("graphics", "max_obj_dist", Def::Float(-1.0)),
    ("graphics", "map_detail", Def::Int(-1)),
    ("graphics", "view_distance", Def::Float(0.0)),
    ("graphics", "mirror_size", Def::Int(256)),
    ("graphics", "mirror_refresh", Def::Str("full")),
    ("graphics", "led_glow", Def::Int(6)),
    ("graphics", "nightmap_glow", Def::Int(6)),
    ("graphics", "atmosphere_brightness", Def::Float(1.0)),
    ("graphics", "led_mips", Def::Float(1.3)),
    // [audio]
    ("audio", "master-volume", Def::Float(1.0)),
    ("audio", "ai-volume", Def::Float(1.0)),
    ("audio", "scenery-volume", Def::Float(1.0)),
    ("audio", "doppler", Def::Bool(true)),
    // [controller]
    ("controller", "deadzone", Def::Float(0.05)),
    ("controller", "ff_enabled", Def::Bool(true)),
    ("controller", "ff_invert", Def::Bool(false)),
    ("controller", "assign", Def::Str("")),
    // [camera]
    ("camera", "fov", Def::Float(0.0)),
    ("camera", "collision", Def::Bool(true)),
    ("camera", "smooth", Def::Bool(true)),
    ("camera", "head_movement", Def::Bool(true)),
    ("camera", "steer_look", Def::Bool(false)),
    ("camera", "steer_look_angle", Def::Float(30.0)),
    ("camera", "steer_look_response", Def::Float(0.25)),
    ("camera", "seat_x", Def::Float(0.0)),
    ("camera", "seat_y", Def::Float(0.0)),
    ("camera", "seat_z", Def::Float(0.0)),
    ("camera", "look_sens", Def::Float(1.0)),
    ("camera", "alt_view", Def::Bool(true)),
    ("camera", "free_look", Def::Bool(false)),
    ("camera", "crosshair", Def::Bool(true)),
    ("camera", "head_tracking", Def::Bool(false)),
    ("camera", "head_tracking_port", Def::Int(4242)),
    ("camera", "head_tracking_invert", Def::Str("")),
    // [vr]
    ("vr", "enabled", Def::Bool(false)),
    ("vr", "scale", Def::Float(0.65)),
    ("vr", "head-smoothing-ms", Def::Float(0.0)),
    ("vr", "mirror-rate", Def::Float(16.0)),
    ("vr", "desktop-mirror", Def::Bool(true)),
    // [launcher]
    ("launcher", "update_check", Def::Bool(true)),
    ("launcher", "update_auto", Def::Bool(false)),
];
